/**
 * API-specific type definitions
 * Re-export commonly used types for convenience
 */

export type {
  ApiError,
  AuthResponse,
  CreateRequest,
  ErrorResponse,
  FieldErrors,
  FilterParams,
  ListParams,
  LoginRequest,
  PaginatedResponse,
  PaginationParams,
  UpdateRequest,
} from '@/types/api'
export type {
  Activity,
  Address,
  AuditLog,
  Authorization,
  BaseEntity,
  CallbackCampaign,
  CallbackCampaignAggregate,
  CallbackCase,
  CallbackOutcome,
  CallbackQuestionSummary,
  Case,
  Client,
  ClientBillingAddress,
  ClientContactInfo,
  ClientStats,
  ClientTag,
  ClinicalNote,
  Contact,
  ContactInfo,
  Contract,
  ContractPricing,
  Diagnosis,
  Document,
  EAPProgramme,
  EligibleMember,
  Engagement,
  EngagementDeliverable,
  EngagementTimeEntry,
  EngagementTimelineEvent,
  Incident,
  IncidentTimelineEvent,
  Industry,
  InvoiceLinePreview,
  KPI,
  KPIAssignment,
  NonCompeteClause,
  Person,
  Provider,
  ProviderEligibility,
  ProviderProfile,
  Questionnaire,
  QuestionnaireOption,
  QuestionnaireQuestion,
  RateCardItem,
  Service,
  ServiceAssignment,
  ServiceSession,
  Survey,
  SurveyAggregate,
  SurveyQuestionSummary,
  Tenant,
  User,
} from '@/types/entities'
export * from '@/types/enums'
