/**
 * Providers fixture (D-Provider v1). Replaced by `/v1/providers` once BE Phase 2 #3 lands.
 *
 * Seeded with ≥5 providers spanning every region for the panel-rendering acceptance gate.
 */

import type { Provider } from '@/types/entities'
import { AccreditationStatus, ProviderRegion, ProviderTier } from '@/types/enums'

export const providersFixture: Provider[] = [
  {
    id: 'prov-001',
    tenant_id: 'tenant-fixture',
    name: 'Nakato Lubega (Counsellor)',
    tier: ProviderTier.T1,
    region: ProviderRegion.KAMPALA,
    email: 'nakato@example.com',
    phone: '+256 700 000 001',
    accreditation: {
      body: 'UCA',
      registration_number: 'UCA/2018/00541',
      status: AccreditationStatus.ACTIVE,
      issued_at: '2018-04-12',
      expires_at: '2026-12-31',
    },
    non_compete_clauses: [
      {
        id: 'nc-001-1',
        client_id: 'fixture-stanbic',
        client_name: 'Stanbic Bank Uganda',
        start_date: '2025-01-01',
        end_date: '2026-12-31',
        regions: [ProviderRegion.KAMPALA],
        notes: 'No solo engagements with Stanbic competitor banks (Kampala only).',
      },
    ],
    tier_audit: [
      {
        id: 'aud-001-1',
        from_tier: ProviderTier.T2,
        to_tier: ProviderTier.T1,
        at: '2025-08-01T09:00:00Z',
        actor: 'Helen Nakato',
        reason: 'Sustained CSAT > 4.6 across 18 months; promoted to anchor pool.',
      },
      {
        id: 'aud-001-2',
        from_tier: null,
        to_tier: ProviderTier.T2,
        at: '2018-05-01T09:00:00Z',
        actor: 'Founders',
        reason: 'Initial onboarding.',
      },
    ],
    created_at: '2018-05-01T09:00:00Z',
    updated_at: '2025-08-01T09:00:00Z',
  },
  {
    id: 'prov-002',
    tenant_id: 'tenant-fixture',
    name: 'Eastern Wellness Group',
    tier: ProviderTier.T2,
    region: ProviderRegion.EASTERN,
    email: 'info@easternwellness.co.ug',
    phone: '+256 711 000 002',
    accreditation: {
      body: 'UCA',
      registration_number: 'UCA/2020/01122',
      status: AccreditationStatus.PENDING_RENEWAL,
      issued_at: '2020-09-15',
      expires_at: '2026-09-14',
    },
    non_compete_clauses: [],
    tier_audit: [
      {
        id: 'aud-002-1',
        from_tier: null,
        to_tier: ProviderTier.T2,
        at: '2020-10-01T09:00:00Z',
        actor: 'Helen Nakato',
        reason: 'Onboarded after vetting.',
      },
    ],
    created_at: '2020-10-01T09:00:00Z',
    updated_at: '2026-04-01T10:00:00Z',
  },
  {
    id: 'prov-003',
    tenant_id: 'tenant-fixture',
    name: 'Northern Counselling Practice',
    tier: ProviderTier.T2,
    region: ProviderRegion.NORTHERN,
    email: 'practice@northerncounsel.co.ug',
    phone: '+256 722 000 003',
    accreditation: {
      body: 'UCA',
      registration_number: 'UCA/2019/00872',
      status: AccreditationStatus.ACTIVE,
      issued_at: '2019-06-01',
      expires_at: '2027-05-31',
    },
    non_compete_clauses: [
      {
        id: 'nc-003-1',
        client_id: 'fixture-hima',
        client_name: 'Hima Cement',
        start_date: '2024-04-01',
        end_date: '2027-03-31',
        regions: [],
        notes: 'Global non-compete with Hima while retainer active.',
      },
    ],
    tier_audit: [
      {
        id: 'aud-003-1',
        from_tier: null,
        to_tier: ProviderTier.T2,
        at: '2019-07-01T09:00:00Z',
        actor: 'Helen Nakato',
        reason: 'Onboarded.',
      },
    ],
    created_at: '2019-07-01T09:00:00Z',
    updated_at: '2024-04-01T09:00:00Z',
  },
  {
    id: 'prov-004',
    tenant_id: 'tenant-fixture',
    name: 'Western Mind Centre',
    tier: ProviderTier.T3,
    region: ProviderRegion.WESTERN,
    email: 'admin@westernmind.co.ug',
    phone: '+256 733 000 004',
    accreditation: {
      body: 'UCA',
      registration_number: 'UCA/2022/01988',
      status: AccreditationStatus.EXPIRED,
      issued_at: '2022-02-20',
      expires_at: '2026-02-19',
    },
    non_compete_clauses: [],
    tier_audit: [
      {
        id: 'aud-004-1',
        from_tier: ProviderTier.T2,
        to_tier: ProviderTier.T3,
        at: '2026-03-01T09:00:00Z',
        actor: 'Helen Nakato',
        reason: 'Accreditation expired; demoted pending renewal.',
      },
      {
        id: 'aud-004-2',
        from_tier: null,
        to_tier: ProviderTier.T2,
        at: '2022-03-01T09:00:00Z',
        actor: 'Helen Nakato',
        reason: 'Onboarded.',
      },
    ],
    created_at: '2022-03-01T09:00:00Z',
    updated_at: '2026-03-01T09:00:00Z',
  },
  {
    id: 'prov-005',
    tenant_id: 'tenant-fixture',
    name: 'Rwenzori Therapy Co-op',
    tier: ProviderTier.T1,
    region: ProviderRegion.CENTRAL,
    email: 'office@rwenzori.co.ug',
    phone: '+256 744 000 005',
    accreditation: {
      body: 'UCA',
      registration_number: 'UCA/2017/00310',
      status: AccreditationStatus.ACTIVE,
      issued_at: '2017-03-10',
      expires_at: '2027-03-09',
    },
    non_compete_clauses: [
      {
        id: 'nc-005-1',
        client_id: 'fixture-equity',
        client_name: 'Equity Bank Uganda',
        start_date: '2023-09-01',
        end_date: '2026-08-31',
        regions: [ProviderRegion.CENTRAL, ProviderRegion.KAMPALA],
        notes: 'Anchor retainer non-compete (Central + Kampala).',
      },
    ],
    tier_audit: [
      {
        id: 'aud-005-1',
        from_tier: ProviderTier.T2,
        to_tier: ProviderTier.T1,
        at: '2023-09-01T09:00:00Z',
        actor: 'Helen Nakato',
        reason: 'Anchor retainer awarded.',
      },
    ],
    created_at: '2017-03-10T09:00:00Z',
    updated_at: '2023-09-01T09:00:00Z',
  },
  {
    id: 'prov-006',
    tenant_id: 'tenant-fixture',
    name: 'Telehealth+ Africa',
    tier: ProviderTier.T2,
    region: ProviderRegion.REMOTE,
    email: 'concierge@telehealthplus.africa',
    phone: '+256 755 000 006',
    accreditation: {
      body: 'UCA',
      registration_number: 'UCA/2024/02510',
      status: AccreditationStatus.ACTIVE,
      issued_at: '2024-01-15',
      expires_at: '2027-01-14',
    },
    non_compete_clauses: [],
    tier_audit: [
      {
        id: 'aud-006-1',
        from_tier: null,
        to_tier: ProviderTier.T2,
        at: '2024-02-01T09:00:00Z',
        actor: 'Helen Nakato',
        reason: 'Onboarded for nationwide remote coverage.',
      },
    ],
    created_at: '2024-02-01T09:00:00Z',
    updated_at: '2025-12-01T10:00:00Z',
  },
]
