/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as TenantsIndexRouteImport } from './routes/tenants/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as PersonsIndexRouteImport } from './routes/persons/index'
import { Route as KpisIndexRouteImport } from './routes/kpis/index'
import { Route as DocumentsIndexRouteImport } from './routes/documents/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ContractsIndexRouteImport } from './routes/contracts/index'
import { Route as ClientsIndexRouteImport } from './routes/clients/index'
import { Route as AuditIndexRouteImport } from './routes/audit/index'
import { Route as UsersNewRouteImport } from './routes/users/new'
import { Route as UsersUserIdRouteImport } from './routes/users/$userId'
import { Route as TenantsNewRouteImport } from './routes/tenants/new'
import { Route as TenantsCreateRouteImport } from './routes/tenants/create'
import { Route as TenantsTenantIdRouteImport } from './routes/tenants/$tenantId'
import { Route as ServicesNewRouteImport } from './routes/services/new'
import { Route as ServicesServiceIdRouteImport } from './routes/services/$serviceId'
import { Route as PersonsNewRouteImport } from './routes/persons/new'
import { Route as PersonsPersonIdRouteImport } from './routes/persons/$personId'
import { Route as ContractsNewRouteImport } from './routes/contracts/new'
import { Route as ContractsContractIdRouteImport } from './routes/contracts/$contractId'
import { Route as ClientsNewRouteImport } from './routes/clients/new'
import { Route as ClientsClientIdRouteImport } from './routes/clients/$clientId'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as TenantsTenantIdEditRouteImport } from './routes/tenants/$tenantId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsIndexRoute = TenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonsIndexRoute = PersonsIndexRouteImport.update({
  id: '/persons/',
  path: '/persons/',
  getParentRoute: () => rootRouteImport,
} as any)
const KpisIndexRoute = KpisIndexRouteImport.update({
  id: '/kpis/',
  path: '/kpis/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsIndexRoute = DocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsIndexRoute = ContractsIndexRouteImport.update({
  id: '/contracts/',
  path: '/contracts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditIndexRoute = AuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersNewRoute = UsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsNewRoute = TenantsNewRouteImport.update({
  id: '/tenants/new',
  path: '/tenants/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsCreateRoute = TenantsCreateRouteImport.update({
  id: '/tenants/create',
  path: '/tenants/create',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsTenantIdRoute = TenantsTenantIdRouteImport.update({
  id: '/tenants/$tenantId',
  path: '/tenants/$tenantId',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesNewRoute = ServicesNewRouteImport.update({
  id: '/services/new',
  path: '/services/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceIdRoute = ServicesServiceIdRouteImport.update({
  id: '/services/$serviceId',
  path: '/services/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonsNewRoute = PersonsNewRouteImport.update({
  id: '/persons/new',
  path: '/persons/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonsPersonIdRoute = PersonsPersonIdRouteImport.update({
  id: '/persons/$personId',
  path: '/persons/$personId',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsNewRoute = ContractsNewRouteImport.update({
  id: '/contracts/new',
  path: '/contracts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsContractIdRoute = ContractsContractIdRouteImport.update({
  id: '/contracts/$contractId',
  path: '/contracts/$contractId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsNewRoute = ClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsTenantIdEditRoute = TenantsTenantIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => TenantsTenantIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/new': typeof ClientsNewRoute
  '/contracts/$contractId': typeof ContractsContractIdRoute
  '/contracts/new': typeof ContractsNewRoute
  '/persons/$personId': typeof PersonsPersonIdRoute
  '/persons/new': typeof PersonsNewRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/services/new': typeof ServicesNewRoute
  '/tenants/$tenantId': typeof TenantsTenantIdRouteWithChildren
  '/tenants/create': typeof TenantsCreateRoute
  '/tenants/new': typeof TenantsNewRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/users/new': typeof UsersNewRoute
  '/audit/': typeof AuditIndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/contracts/': typeof ContractsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/documents/': typeof DocumentsIndexRoute
  '/kpis/': typeof KpisIndexRoute
  '/persons/': typeof PersonsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/tenants/': typeof TenantsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/tenants/$tenantId/edit': typeof TenantsTenantIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/new': typeof ClientsNewRoute
  '/contracts/$contractId': typeof ContractsContractIdRoute
  '/contracts/new': typeof ContractsNewRoute
  '/persons/$personId': typeof PersonsPersonIdRoute
  '/persons/new': typeof PersonsNewRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/services/new': typeof ServicesNewRoute
  '/tenants/$tenantId': typeof TenantsTenantIdRouteWithChildren
  '/tenants/create': typeof TenantsCreateRoute
  '/tenants/new': typeof TenantsNewRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/users/new': typeof UsersNewRoute
  '/audit': typeof AuditIndexRoute
  '/clients': typeof ClientsIndexRoute
  '/contracts': typeof ContractsIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/documents': typeof DocumentsIndexRoute
  '/kpis': typeof KpisIndexRoute
  '/persons': typeof PersonsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/tenants': typeof TenantsIndexRoute
  '/users': typeof UsersIndexRoute
  '/tenants/$tenantId/edit': typeof TenantsTenantIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/new': typeof ClientsNewRoute
  '/contracts/$contractId': typeof ContractsContractIdRoute
  '/contracts/new': typeof ContractsNewRoute
  '/persons/$personId': typeof PersonsPersonIdRoute
  '/persons/new': typeof PersonsNewRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/services/new': typeof ServicesNewRoute
  '/tenants/$tenantId': typeof TenantsTenantIdRouteWithChildren
  '/tenants/create': typeof TenantsCreateRoute
  '/tenants/new': typeof TenantsNewRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/users/new': typeof UsersNewRoute
  '/audit/': typeof AuditIndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/contracts/': typeof ContractsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/documents/': typeof DocumentsIndexRoute
  '/kpis/': typeof KpisIndexRoute
  '/persons/': typeof PersonsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/tenants/': typeof TenantsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/tenants/$tenantId/edit': typeof TenantsTenantIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/signup'
    | '/clients/$clientId'
    | '/clients/new'
    | '/contracts/$contractId'
    | '/contracts/new'
    | '/persons/$personId'
    | '/persons/new'
    | '/services/$serviceId'
    | '/services/new'
    | '/tenants/$tenantId'
    | '/tenants/create'
    | '/tenants/new'
    | '/users/$userId'
    | '/users/new'
    | '/audit/'
    | '/clients/'
    | '/contracts/'
    | '/dashboard/'
    | '/documents/'
    | '/kpis/'
    | '/persons/'
    | '/services/'
    | '/sessions/'
    | '/tenants/'
    | '/users/'
    | '/tenants/$tenantId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/signup'
    | '/clients/$clientId'
    | '/clients/new'
    | '/contracts/$contractId'
    | '/contracts/new'
    | '/persons/$personId'
    | '/persons/new'
    | '/services/$serviceId'
    | '/services/new'
    | '/tenants/$tenantId'
    | '/tenants/create'
    | '/tenants/new'
    | '/users/$userId'
    | '/users/new'
    | '/audit'
    | '/clients'
    | '/contracts'
    | '/dashboard'
    | '/documents'
    | '/kpis'
    | '/persons'
    | '/services'
    | '/sessions'
    | '/tenants'
    | '/users'
    | '/tenants/$tenantId/edit'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/auth/signup'
    | '/clients/$clientId'
    | '/clients/new'
    | '/contracts/$contractId'
    | '/contracts/new'
    | '/persons/$personId'
    | '/persons/new'
    | '/services/$serviceId'
    | '/services/new'
    | '/tenants/$tenantId'
    | '/tenants/create'
    | '/tenants/new'
    | '/users/$userId'
    | '/users/new'
    | '/audit/'
    | '/clients/'
    | '/contracts/'
    | '/dashboard/'
    | '/documents/'
    | '/kpis/'
    | '/persons/'
    | '/services/'
    | '/sessions/'
    | '/tenants/'
    | '/users/'
    | '/tenants/$tenantId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  ClientsClientIdRoute: typeof ClientsClientIdRoute
  ClientsNewRoute: typeof ClientsNewRoute
  ContractsContractIdRoute: typeof ContractsContractIdRoute
  ContractsNewRoute: typeof ContractsNewRoute
  PersonsPersonIdRoute: typeof PersonsPersonIdRoute
  PersonsNewRoute: typeof PersonsNewRoute
  ServicesServiceIdRoute: typeof ServicesServiceIdRoute
  ServicesNewRoute: typeof ServicesNewRoute
  TenantsTenantIdRoute: typeof TenantsTenantIdRouteWithChildren
  TenantsCreateRoute: typeof TenantsCreateRoute
  TenantsNewRoute: typeof TenantsNewRoute
  UsersUserIdRoute: typeof UsersUserIdRoute
  UsersNewRoute: typeof UsersNewRoute
  AuditIndexRoute: typeof AuditIndexRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
  ContractsIndexRoute: typeof ContractsIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DocumentsIndexRoute: typeof DocumentsIndexRoute
  KpisIndexRoute: typeof KpisIndexRoute
  PersonsIndexRoute: typeof PersonsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
  TenantsIndexRoute: typeof TenantsIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants/': {
      id: '/tenants/'
      path: '/tenants'
      fullPath: '/tenants/'
      preLoaderRoute: typeof TenantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persons/': {
      id: '/persons/'
      path: '/persons'
      fullPath: '/persons/'
      preLoaderRoute: typeof PersonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kpis/': {
      id: '/kpis/'
      path: '/kpis'
      fullPath: '/kpis/'
      preLoaderRoute: typeof KpisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/': {
      id: '/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof DocumentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts/': {
      id: '/contracts/'
      path: '/contracts'
      fullPath: '/contracts/'
      preLoaderRoute: typeof ContractsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit/': {
      id: '/audit/'
      path: '/audit'
      fullPath: '/audit/'
      preLoaderRoute: typeof AuditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/new': {
      id: '/users/new'
      path: '/users/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof UsersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants/new': {
      id: '/tenants/new'
      path: '/tenants/new'
      fullPath: '/tenants/new'
      preLoaderRoute: typeof TenantsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants/create': {
      id: '/tenants/create'
      path: '/tenants/create'
      fullPath: '/tenants/create'
      preLoaderRoute: typeof TenantsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants/$tenantId': {
      id: '/tenants/$tenantId'
      path: '/tenants/$tenantId'
      fullPath: '/tenants/$tenantId'
      preLoaderRoute: typeof TenantsTenantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/new': {
      id: '/services/new'
      path: '/services/new'
      fullPath: '/services/new'
      preLoaderRoute: typeof ServicesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$serviceId': {
      id: '/services/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/services/$serviceId'
      preLoaderRoute: typeof ServicesServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persons/new': {
      id: '/persons/new'
      path: '/persons/new'
      fullPath: '/persons/new'
      preLoaderRoute: typeof PersonsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persons/$personId': {
      id: '/persons/$personId'
      path: '/persons/$personId'
      fullPath: '/persons/$personId'
      preLoaderRoute: typeof PersonsPersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts/new': {
      id: '/contracts/new'
      path: '/contracts/new'
      fullPath: '/contracts/new'
      preLoaderRoute: typeof ContractsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts/$contractId': {
      id: '/contracts/$contractId'
      path: '/contracts/$contractId'
      fullPath: '/contracts/$contractId'
      preLoaderRoute: typeof ContractsContractIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/new': {
      id: '/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof ClientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants/$tenantId/edit': {
      id: '/tenants/$tenantId/edit'
      path: '/edit'
      fullPath: '/tenants/$tenantId/edit'
      preLoaderRoute: typeof TenantsTenantIdEditRouteImport
      parentRoute: typeof TenantsTenantIdRoute
    }
  }
}

interface TenantsTenantIdRouteChildren {
  TenantsTenantIdEditRoute: typeof TenantsTenantIdEditRoute
}

const TenantsTenantIdRouteChildren: TenantsTenantIdRouteChildren = {
  TenantsTenantIdEditRoute: TenantsTenantIdEditRoute,
}

const TenantsTenantIdRouteWithChildren = TenantsTenantIdRoute._addFileChildren(
  TenantsTenantIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  ClientsClientIdRoute: ClientsClientIdRoute,
  ClientsNewRoute: ClientsNewRoute,
  ContractsContractIdRoute: ContractsContractIdRoute,
  ContractsNewRoute: ContractsNewRoute,
  PersonsPersonIdRoute: PersonsPersonIdRoute,
  PersonsNewRoute: PersonsNewRoute,
  ServicesServiceIdRoute: ServicesServiceIdRoute,
  ServicesNewRoute: ServicesNewRoute,
  TenantsTenantIdRoute: TenantsTenantIdRouteWithChildren,
  TenantsCreateRoute: TenantsCreateRoute,
  TenantsNewRoute: TenantsNewRoute,
  UsersUserIdRoute: UsersUserIdRoute,
  UsersNewRoute: UsersNewRoute,
  AuditIndexRoute: AuditIndexRoute,
  ClientsIndexRoute: ClientsIndexRoute,
  ContractsIndexRoute: ContractsIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DocumentsIndexRoute: DocumentsIndexRoute,
  KpisIndexRoute: KpisIndexRoute,
  PersonsIndexRoute: PersonsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  SessionsIndexRoute: SessionsIndexRoute,
  TenantsIndexRoute: TenantsIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
